version: '3'

services:
  web:
    image: "nginx:1.21.4"
    hostname: nginx_1-21-4_localhost
    deploy:
      restart_policy:
        condition: none
    volumes:
      - /mnt/c/Users/cneves/source/repos/LotFac/_new3/:/usr/share/nginx/html/
    ports:
      - "8888:80"
