version: '3.9'

services:
  web:
    image: "nginx:1.21.4"
    hostname: nginx_1-21-4_localhost
    deploy:
      restart_policy:
        condition: none
    volumes:
      - /local/path/:/usr/share/nginx/html/
    ports:
      - "8888:80"
networks:
  default:
    name: bridge
    external: true
