version: '3.8'

services:
  mysql:
    image: mysql:5.7.42
    container_name: my_mysql
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - my_network
    deploy:
      restart_policy:
        condition: none
    volumes:
      - ./custom-init.sql:/docker-entrypoint-initdb.d/custom-init.sql
networks:
  my_network:
